### ISSUE TITLE
Add Dynamic Colors, Advanced Animations, and Enhanced Border Radius Effects

### ISSUE THREAD

**Issue by sarveshsinghthakur** [sarveshsinghthakur/Portfolio#1]
#### 1. Dynamic Color Theme System
Add a dynamic color theme system with the following features:

```css
:root {
  --primary-color: #0057f8;
  --secondary-color: #003d99;
  --background-color: #f8f9fa;
  --text-color: #333;
  --accent-color: #2980b9;
}

/* Add Dark Mode Colors */
[data-theme="dark"] {
  --primary-color: #66a3ff;
  --secondary-color: #004bb5;
  --background-color: #1a1a1a;
  --text-color: #f0f0f0;
  --accent-color: #3498db;
}

/* Add color transition for smooth theme switching */
* {
  transition: background-color 0.3s ease, color 0.3s ease;
}
```

Add a theme toggle button in the navigation bar:
```html
<button id="theme-toggle" class="theme-toggle">
  <i class="fas fa-moon"></i>
</button>
```

##### A. Scroll-triggered Animations
```css
.fade-in-up {
  opacity: 0;
  transform: translateY(30px);
  transition: opacity 0.6s ease-out, transform 0.6s ease-out;
}

.fade-in-up.visible {
  opacity: 1;
  transform: translateY(0);
}

.slide-in-right {
  opacity: 0;
  transform: translateX(30px);
  transition: opacity 0.6s ease-out, transform 0.6s ease-out;
}

.slide-in-right.visible {
  opacity: 1;
  transform: translateX(0);
}
```

##### B. Hover Effects for Cards
```css
.card {
  transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1),
              box-shadow 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.card:hover {
  transform: translateY(-10px) scale(1.02);
  box-shadow: 0 15px 30px rgba(0, 87, 248, 0.15);
}
```

##### C. Gradient Animation for Buttons
```css
.btn-primary {
  background: linear-gradient(45deg, #0057f8, #003d99);
  background-size: 200% 200%;
  animation: gradientShift 5s ease infinite;
}

@keyframes gradientShift {
  0% { background-position: 0% 50%; }
  50% { background-position: 100% 50%; }
  100% { background-position: 0% 50%; }
}
```

##### A. Custom Border Radius for Cards
```css
.card {
  border-radius: 20px 5px 20px 5px;
  overflow: hidden;
}

.skills-card {
  border-radius: 30px 30px 5px 30px;
}

.project-card {
  border-radius: 15px 30px 15px 30px;
}
```

##### B. Blob-shaped Elements
```css
.blob-shape {
  border-radius: 71% 29% 41% 59% / 59% 43% 57% 41%;
  transition: border-radius 0.5s ease;
}

.blob-shape:hover {
  border-radius: 63% 37% 54% 46% / 43% 51% 49% 57%;
}
```

##### A. Parallax Scrolling Effect
```css
.parallax-section {
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
```

##### B. Progress Bar Animation
```css
.skill-progress {
  width: 0;
  height: 8px;
  background: linear-gradient(90deg, #0057f8, #003d99);
  border-radius: 4px;
  transition: width 1s ease-in-out;
}

.skill-progress.visible {
  width: var(--progress-width);
}
```

### Implementation Steps:

1. Add the CSS variables and theme toggle functionality
2. Implement scroll-triggered animations using Intersection Observer API
3. Update card and button styles with new hover effects
4. Add custom border radius styles to different sections
5. Implement parallax scrolling for hero section
6. Add progress bar animations for skills section
7. Add smooth transitions between different states

### JavaScript Requirements:

```javascript
// Theme Toggle
const themeToggle = document.getElementById('theme-toggle');
themeToggle.addEventListener('click', () => {
  document.body.dataset.theme = document.body.dataset.theme === 'dark' ? 'light' : 'dark';
});

// Scroll Animations
const observerOptions = {
  threshold: 0.1
};

const observer = new IntersectionObserver((entries) => {
  entries.forEach(entry => {
    if (entry.isIntersecting) {
      entry.target.classList.add('visible');
    }
  });
}, observerOptions);

document.querySelectorAll('.fade-in-up, .slide-in-right, .skill-progress').forEach((el) => observer.observe(el));
```

These improvements will make your portfolio more engaging and modern while maintaining good performance and accessibility. The changes include smooth animations, dynamic color themes, and interesting geometric shapes that will make your portfolio stand out.
